#将静态内容部署到GitHub页面的简单工作流程
名称：将静态内容部署到页面: 将静态内容部署到页面

在……之上：:
#在以默认分支为目标的推送上运行#在以默认分支为目标的推送上运行
推：:
分支机构：["main"]: ["主要"]

#允许您从“操作”选项卡手动运行此工作流#允许您从[动作]索引标签手动执行此工作流程
工作流程分派(_D)：:

#设置GitHub_TOKEN的权限以允许部署到GitHub页面
权限：:
内容：已读: 读
页面：写入: 写
id-token：写入: 写

#只允许一个并发部署，跳过正在运行和最新排队之间排队的运行。
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
